backend:
  name: github
  repo: DimbelMe/Perkyo
  branch: main

media_folder: "public/img/gallery"
public_folder: "/img/gallery"

collections:
  - name: "objects"
    label: "Gallery Objects"
    folder: "src/Content/Objects"
    create: true
    format: "json"
    slug: "{{slug}}"

    fields:
      - label: "Name"
        name: "name"
        widget: "string"

      - label: "Category"
        name: "categoria"
        widget: "select"
        options:
          - "Anime"
          - "Peliculas"
          - "Series"
          - "Videojuegos"
          - "Otros"

      - label: "Back Image"
        name: "imgBack"
        widget: "image"

      - label: "Front Image"
        name: "imgFront"
        widget: "image"